# Generated by Django 5.0.2 on 2024-02-21 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('Category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Name', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'book_category',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_description', models.TextField(null=True)),
                ('book_image', models.ImageField(upload_to='book-images/')),
                ('book_price', models.IntegerField()),
                ('book_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.bookcategory')),
                ('book_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.userdata')),
            ],
        ),
    ]
