# Generated by Django 5.0.2 on 2024-02-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookdata',
            table='book_data',
        ),
    ]
