# Generated by Django 5.0.2 on 2024-02-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_bookdata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='book_price',
            field=models.CharField(max_length=10),
        ),
    ]
