# Generated by Django 5.0.2 on 2024-02-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_bookdatamodel_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='authordatamodel',
            name='author_login',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='authordatamodel',
            name='author_password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
