# Generated by Django 5.0.2 on 2024-02-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_addtocartmodel_buynowmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocartmodel',
            old_name='product_name',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='buynowmodel',
            old_name='product_name',
            new_name='product_id',
        ),
    ]
